class GameConfig
  DEBUG = TRUE
  USER_DEBUG = false

  MAP_WIDTH = 800
  MAP_HEIGHT = 600

  BOTTOM_HEIGHT = 37

  STATUS_BAR_Y = 600 - 21
  STATUS_BAR_WIDTH = 800
  STATUS_BAR_HEIGHT = 58

  WHOLE_WIDTH = MAP_WIDTH
  WHOLE_HEIGHT = STATUS_BAR_Y + STATUS_BAR_HEIGHT

  CHAT_BOARD_TOP = MAP_HEIGHT - 120
  CHAT_BOARD_LEFT = 60
  CHAT_BOARD_WIDTH = 436 - 60
  CHAT_BOARD_HEIGHT = 120

  # 每秒产生食物个数
  FOOD_GEN_PER_SECOND = 0.15

  RUNNING_HP_DEC = 0.2
  REST_HP_INC = 0.05

  ROLE_INTAKE = 0.2
end